#!/bin/sh

python ./gbe_start.py 1 &
python ./gbe_start.py 2 &
python ./gbe_start.py 3 &
##python ./gbe_start.py 4 &
python ./gbe_start.py 5 &
python ./gbe_start.py 6 &
python ./gbe_start.py 7 &
python ./gbe_start.py 8 &
python ./gbe_start.py 9 &
python ./gbe_start.py 10 &
python ./gbe_start.py 11 &
python ./gbe_start.py 12 &
python ./gbe_start.py 13 &
python ./gbe_start.py 14 &
python ./gbe_start.py 15 &
python ./gbe_start.py 16 &
python ./gbe_start.py 17 &
python ./gbe_start.py 18 &
python ./gbe_start.py 19 &
python ./gbe_start.py 20 &
python ./gbe_start.py 21 &
python ./gbe_start.py 22 &
python ./gbe_start.py 23 &
python ./gbe_start.py 24 &
python ./gbe_start.py 25 &
python ./gbe_start.py 26 &
python ./gbe_start.py 27 &
python ./gbe_start.py 28 &
python ./gbe_start.py 29 &
python ./gbe_start.py 30 &
python ./gbe_start.py 31 &
python ./gbe_start.py 32 &
python ./gbe_start.py 33 &
python ./gbe_start.py 34 &
python ./gbe_start.py 35 &
python ./gbe_start.py 36 &
python ./gbe_start.py 37 &
python ./gbe_start.py 38 &
