#!/bin/sh

python ./gbe_halt.py 1 $1 &
python ./gbe_halt.py 2 $1 &
python ./gbe_halt.py 3 $1 &
python ./gbe_halt.py 4 $1 &
python ./gbe_halt.py 5 $1 &
python ./gbe_halt.py 6 $1 &
python ./gbe_halt.py 7 $1 &
python ./gbe_halt.py 8 $1 &
python ./gbe_halt.py 9 $1 &
python ./gbe_halt.py 10 $1 &
python ./gbe_halt.py 11 $1 &
python ./gbe_halt.py 12 $1 &
python ./gbe_halt.py 13 $1 &
python ./gbe_halt.py 14 $1 &
python ./gbe_halt.py 15 $1 &
python ./gbe_halt.py 16 $1 &
python ./gbe_halt.py 17 $1 &
python ./gbe_halt.py 18 $1 &
python ./gbe_halt.py 19 $1 &
python ./gbe_halt.py 20 $1 &
python ./gbe_halt.py 21 $1 &
python ./gbe_halt.py 22 $1 &
python ./gbe_halt.py 23 $1 &
python ./gbe_halt.py 24 $1 &
python ./gbe_halt.py 25 $1 &
python ./gbe_halt.py 26 $1 &
python ./gbe_halt.py 27 $1 &
python ./gbe_halt.py 28 $1 &
python ./gbe_halt.py 29 $1 &
python ./gbe_halt.py 30 $1 &
python ./gbe_halt.py 31 $1 &
python ./gbe_halt.py 32 $1 &
python ./gbe_halt.py 33 $1 &
python ./gbe_halt.py 34 $1 &
python ./gbe_halt.py 35 $1 &
python ./gbe_halt.py 36 $1 &
python ./gbe_halt.py 37 $1 &
python ./gbe_halt.py 38 $1 &
